### ISSUE TITLE
GestureHandler already initialized for root view

### ISSUE THREAD

**Issue by ethantran** [react-navigation/stack#136] opened 2019-05-28 16:09 UTC
I will occasionally get this error, but I am not sure how to reproduce it. All I know is that it is related to the stack navigator and how it implements react native gesture handler. When I switch it to another navigator like bottom tab, it does not throw error. I can only prevent the error temporarily by closing the app and opening it back up.

Platform: Android
```
"react": "16.8.3",
"react-native": "0.59.5",
"react-native-gesture-handler": "^1.2.1",
"react-navigation": "3.9.1"
```

```
const MainNavigator = createBottomTabNavigator({
  Home: {
    screen: HomeScreen
  }
});
export const AppContainer = createAppContainer(MainNavigator);
```

**Comment by satya164** [comment] 2019-07-08 10:17
Closing due to no repro. If this still occurs with the latest versions, please open a new issue with a repro.

**Closed by satya164** 2019-07-08 10:17 UTC

**Comment by AilsonFreire** [comment] 2019-09-04 17:01
I am having the same problem. I don´t know why.

**Comment by Nagibaba** [comment] 2019-09-06 13:24
I restarted Metro Bundler. Error gone

**Comment by SwordElucidator** [comment] 2019-09-11 11:14
Any update?

**Comment by mikebouwmans** [comment] 2019-10-03 09:07
I have this error aswell at random times. Cant seem te reproduce it.

**Comment by yaghami** [comment] 2019-10-18 14:40
Just try close and reopening the app. Solved for me.

**Comment by angel-luis** [comment] 2019-11-28 19:28
Same here, after restart Expo the error gone. I didn't touch the code.

Just developing a starter project with latest RN and RNN@next.

**Comment by web-2017** [comment] 2020-02-13 09:27
just restart your app on device, Metro Bundler, error should gone
