### ISSUE TITLE
CardAnimationContext only working for opening cards?

### ISSUE THREAD

**Issue by saaymeen** [react-navigation/stack#391] opened 2020-02-03 08:19 UTC
Hi! I have a question/issue on using the CardAnimationContext.Consumer to animate a View in the initial Route when transitioning to another route (Card) in the same StackNavigator created with CreateStackNavigator.

**Current Behavior**
CardAnimationContext does not work for the initial route, but for the new route, it does (as in the example).

- What code are you running and what is happening?
[Example Code](https://github.com/react-navigation/stack/blob/master/example/src/StackAnimationConsumerStack.tsx)

**Expected Behavior**

- What do you expect should be happening?
Being able to animate views in the initial route on route change.

**How to reproduce**
In the example, try to animate any property of the View for the initial route (ListScreen Component) using CardAnimationContext.Consumer (see other routes).

Here is a [Snack](https://snack.expo.io/BkxE4iBGL) addressing this issue. The text on the initial screen does not get animated.

Is there another way of how this should be done? Cheers and thanks for your help!

**Comment by satya164** [comment] 2020-02-03 15:07
It gets you the animation context for the card you're in. The initial route doesn't animate so you don't see any changes. The animation you see is the parent navigator's screen animating.

If you need to animate based on parent navigator's animation state, you'll need to wrap your navigator in a component to access and pass that context down manually, or, reduce your nesting unless you actually need it.

Closing since this is the expected behavior.

**Closed by satya164** 2020-02-03 15:07 UTC
