### ISSUE TITLE
isFocused doesn't update for screen after coming back from another screen quickly

### ISSUE THREAD

**Issue by tedcurrent** [react-navigation/stack#359] opened 2020-01-20 08:29 UTC
**Current Behavior**
isFocused doesn't update for screen after coming back from another screen quickly. 

This is what we have
```
const AppStack = createStackNavigator(
  {
    TabNavigator,
    Post,
  }
)
```
`TabNavigator` is as follows
```
const TabNavigator = createBottomTabNavigator(
  {
    Home: {
      screen: Home,
      navigationOptions: {
        tabBarButtonComponent: ({ focused, onPress }) => (
          <NavButton name="home" focused={focused} onPress={onPress} />
        )
      }
    }
  },
  {
    initialRouteName: 'Home',
    backBehavior: 'none'
  }
)
``` 
`Home` and `Post` are simple function components where `Home` is interested in `navigation.isFocused()` to run some code. After navigating to`Post` from `Home` and swiping back, navigation returns `false` for the focused state for `Home`. This is of course wrong.

**Expected Behavior**
`navigation.isFocused()` should be in sync with what's on the screen. In the example above, `Home` is focused and the value should be `true`.

**How to reproduce**
- Update from `2.0.0-alpha.42` to `2.0.1` and see focused break. Same is reproducible with ANY version after `2.0.1`.
- See this issue from `react-navigation/tabs` https://github.com/react-navigation/tabs/issues/236

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | latest
| react-navigation               | 4.0.10
| react-navigation-stack         | 2.0.15
| react-native-gesture-handler   | 1.5.3
| react-native-safe-area-context | 0.6.2
| react-native-screens           | huh?
| react-native                   | latest
| expo                           | -
| node                           | 10.15.3
| npm or yarn                    | 1.19.1

**Comment by satya164** [comment] 2020-01-23 12:04
> In the example above, Home is focused and the value should be true.

Where are you using `navigation.isFocused()` in your example? Please provide full repro

**Comment by tedcurrent** [comment] 2020-01-23 15:06
@satya164 See here: https://github.com/tedcurrent/react-native-stack-issue-repro

**Comment by tedcurrent** [comment] 2020-02-10 07:35
@satya164 have you had a chance to look at this yet?

**Comment by satya164** [comment] 2020-02-10 07:42
I can't repro your issue with the latest version https://snack.expo.io/rkbLFKCGU

![Kapture 2020-02-10 at 8 41 22](https://user-images.githubusercontent.com/1174278/74129968-3066f500-4be1-11ea-9757-ff942e26d70d.gif)

**Comment by tedcurrent** [comment] 2020-02-10 11:04
@satya164 It started working for me after updating too and I was happy for a second. However, now I added `react-navigation-tabs` in (just to simulate more closely what we have in prod) and it broke. Can you test https://github.com/tedcurrent/react-native-stack-issue-repro again? Also please see the issue in tabs linked above.

See gif below. Fast swipe breaks, Slow swipe fixes.

![react-navigation-issue](https://user-images.githubusercontent.com/7895034/74144592-b5fc9c00-4c05-11ea-96ff-a2d5acd46068.gif)

**Comment by satya164** [comment] 2020-02-10 16:48
Duplicate of https://github.com/react-navigation/react-navigation/issues/4867

**Closed by satya164** 2020-02-10 16:48 UTC
