### ISSUE TITLE
NavigationStackOptions seems to want a string, not a JSX Element

### ISSUE THREAD

**Issue by stefanmatar** [react-navigation/stack#230] opened 2019-09-19 09:55 UTC
### Current Behavior

I need to do

```
headerBackground: (
            <SafeAreaView style={[{backgroundColor: 'black'}]}>
                <StatusBar barStyle="light-content" backgroundColor="white"/>
            </SafeAreaView>
    ) as unknown as string
```

### Expected Behavior

I want to do

```
headerBackground: (
            <SafeAreaView style={[{backgroundColor: 'black'}]}>
                <StatusBar barStyle="light-content" backgroundColor="white"/>
            </SafeAreaView>
    ) 
```
Without ~~as unknown as string~~

### How to reproduce

Try to set `headerBackground` in any navigationOptions. It you set it as a `string`, the code fails because the compiler says strings need to be rendered in a `<Text>` Element. If you pass an `<Element>` to the headerBackground, you need to tell Typescript `as unknown as string`, because it is defined as such:

```
export declare type NavigationStackOptions = {
    headerBackground?: string;
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.0
| react-native     | 0.60.3
| node             | 11.6.0
| npm or yarn      | 6.11.3

**Comment by edmundojr** [comment] 2019-09-20 14:51
Same happening for me with `headerTitle` and `headerLeft`. Still works and renders the component, but complains about typings. `as unknown as string` does the job for me.

**Comment by satya164** [comment] 2019-09-23 20:16
Duplicate of #225

**Closed by satya164** 2019-09-23 20:16 UTC
