### ISSUE TITLE
[v2.0.0-alpha.21+] Android blank stack

### ISSUE THREAD

**Issue by ARDcode** [react-navigation/stack#259] opened 2019-10-12 19:38 UTC
After update to v2.0.0-alpha.21-26 all screen in createBottomTabNavigator are empty without header and content. But on alpha20 all are well.

**Comment by satya164** [comment] 2019-10-16 12:30
Please provide minimal repro

**Comment by sazanow** [comment] 2019-11-04 14:49
Have a similar issue. Using createSwitchNavigator with the v2.0.0-alpha.21+.

`const AppNavigator = createReduxContainer(
  createAppContainer(
    createSwitchNavigator(
      {
        AuthLoading: LoginLoader,
        App: StackedAppNavigator,
        Auth: StackedAuthNavigator,
      },
      {
        initialRouteName: 'AuthLoading',
      },
    ),
  ),
  'root',
);`

In IOS works fine but on Android when I get a white screen after calling `this.props.navigation.navigate('Auth');`.

**Comment by el-lsan** [comment] 2019-11-05 11:38
Facing the same issue!

### Environment
```
"react": "16.9.0",
"react-native": "0.61.2",
"react-navigation": "^4.0.10",
"react-navigation-stack": "2.0.0-alpha.34",
"react-navigation-tabs": "^2.5.6",
"react-navigation-redux-helpers": "^4.0.1",
```

**Comment by sebinq** [comment] 2019-11-15 14:45
Can confirm I'm facing this issue even with "react-navigation-stack": "2.0.0-alpha.37",

My use case is wrapping BottomNavigator with error boundary then I have empty screen. (But it is working fine with react-navigation-stack alpha.20)

```js
... other Stacks

const PreferencesStack = createStackNavigator(
  {
    DetailsSearch: DetailsSearchScreen,
    CampInfo: CampInfoScreen
  },
  getStackConfig({ initialRouteName: "DetailsSearch" })
);

const ScreensWithoutBottomNavigator = ["CountryMap", "GpsMap"];
const BaseNavigator = createBottomTabNavigator(
  {
    Home: HomeStack,
    Prefs: PrefsStack,
    Bookmarks: BookmarksStack
  {
    initialRouteName: "Home",
    defaultNavigationOptions: ({ navigation }) => ({
      tabBarIcon: ({ horizontal, tintColor }) => (
        <TapBarIcon
          horizontal={horizontal}
          navigation={navigation}
          tintColor={tintColor}
        />
      )
    }),
    tabBarOptions: {
        ...
        elevation: 0
      }
    }
  }
);

class AppNavigator extends PureComponent {
  static router = BaseNavigator.router;

  render() {
    return (
      <ErrorBoundary {...this.props}>
        <BaseNavigator {...this.props} />
      </ErrorBoundary>
    );
  }
}

export default createAppContainer(AppNavigator);
```

Code above is not working with react-navigation-stack newer than 0.20

**Comment by sebinq** [comment] 2019-11-17 15:33
@satya164 is this enough to reproduce or shall I prepare complete app?

**Comment by ARDcode** [comment] 2019-11-18 08:39
@satya164 this problem on Android after using **react-native-safe-area-context**

**Comment by ajanauskas** [comment] 2019-11-23 20:28
Solved issue myself by moving adding `<SafeAreaProvider>` from `react-native-safe-area-context` as top most component

**Comment by nicolashemonic** [comment] 2019-12-17 15:33
Hello everyone,
After migrating to latest version of React Native (0.6+) and React Navigation (4+) I'm facing a similar issue reproducible with a very simple example [6520](https://github.com/react-navigation/react-navigation/issues/6520)

**Comment by satya164** [comment] 2020-01-23 15:04
Closing since this shouldn't be an issue in latest version.

**Closed by satya164** 2020-01-23 15:04 UTC
Labels: needs more info
